import type { ExcavationResult } from "../types.js";

/**
 * Generates a written developer career narrative from excavation data.
 * Creates a readable story of growth over time.
 */
export function generateStory(narrative: string, excavation: ExcavationResult): string {
  const parts: string[] = [];

  parts.push("# Your Developer Story\n");
  parts.push("Generated by DevScore.ai — from your actual commits and projects.\n");

  // Overview
  parts.push("## Overview\n");
  parts.push(`Over **${excavation.totalCommits} commits** across **${excavation.totalRepos} repositories**, your developer story unfolds:\n`);

  // Chapters
  for (let i = 0; i < excavation.chapters.length; i++) {
    const chapter = excavation.chapters[i];
    parts.push(`## ${chapter.title} (${chapter.period})\n`);
    parts.push(`${chapter.narrative}\n`);

    if (chapter.highlights.length > 0) {
      parts.push("**Highlights:**\n");
      for (const h of chapter.highlights) {
        parts.push(`- ${h}`);
      }
      parts.push("");
    }

    if (chapter.score !== undefined) {
      parts.push(`> **DevScore: ${chapter.score}/10**\n`);
    }
  }

  // Language Evolution
  if (excavation.languageEvolution.length > 0) {
    parts.push("## Language Evolution\n");
    parts.push("| Year | Languages |");
    parts.push("|------|-----------|");
    for (const evo of excavation.languageEvolution) {
      const langs = Object.entries(evo.languages)
        .sort(([, a], [, b]) => b - a)
        .slice(0, 4)
        .map(([l, p]) => `${l} (${p}%)`)
        .join(", ");
      parts.push(`| ${evo.year} | ${langs} |`);
    }
    parts.push("");
  }

  // Peak Productivity
  parts.push("## Peak Productivity\n");
  parts.push(`Your most productive period was **${excavation.peakProductivity.period}** with an average of **${excavation.peakProductivity.avgCommitsPerWeek} commits per week**.\n`);

  // Code Patterns
  const goodPatterns = excavation.codePatterns.filter((p) => p.type === "good");
  const badPatterns = excavation.codePatterns.filter((p) => p.type === "bad");

  if (goodPatterns.length > 0) {
    parts.push("## ✅ Strengths Detected\n");
    for (const p of goodPatterns) {
      parts.push(`- **${p.pattern}** — occurred ${p.frequency} times`);
    }
    parts.push("");
  }

  if (badPatterns.length > 0) {
    parts.push("## ⚠️ Areas to Improve\n");
    for (const p of badPatterns) {
      parts.push(`- **${p.pattern}** — occurred ${p.frequency} times. Consider addressing this.`);
    }
    parts.push("");
  }

  // Full narrative
  parts.push("## Your Story\n");
  parts.push(narrative);
  parts.push("");

  // Forward look
  parts.push("## Where You're Headed\n");
  parts.push("Based on your trajectory and growth pattern, you're building toward ");
  if (excavation.totalRepos >= 10 && excavation.totalCommits >= 500) {
    parts.push("a senior engineering profile. Continue deepening your expertise in your primary stack while exploring adjacent technologies.\n");
  } else if (excavation.totalRepos >= 5) {
    parts.push("a strong mid-level profile. Focus on code quality, testing, and documentation to accelerate to senior level.\n");
  } else {
    parts.push("a solid foundation. Keep building, and consider contributing to open source to broaden your experience.\n");
  }

  parts.push("---\n");
  parts.push(`_Generated by DevScore.ai on ${new Date().toLocaleDateString()}_\n`);

  return parts.join("\n");
}
