import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 120;

interface FixFile {
  path: string;
  content: string;
  description: string;
  icon: string;
  critical: boolean;
}

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    const token = authHeader?.replace("Bearer ", "");

    if (!token) {
      return NextResponse.json(
        { error: "GitHub token is required. Connect your GitHub account first." },
        { status: 401 }
      );
    }

    const { repoFullName, fixes, defaultBranch } = await req.json();

    if (!repoFullName || !fixes || fixes.length === 0) {
      return NextResponse.json(
        { error: "Repository and fixes are required" },
        { status: 400 }
      );
    }

    const [owner, repo] = repoFullName.split("/");
    const branch = `devscore-fix-${Date.now()}`;

    // Step 1: Get the default branch SHA
    const refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${defaultBranch || "main"}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github.v3+json",
        },
      }
    );

    if (!refRes.ok) {
      const err = await refRes.json().catch(() => ({}));
      const msg = err.message || `GitHub API returned ${refRes.status}`;
      if (refRes.status === 401) {
        return NextResponse.json(
          { error: "Your GitHub token is invalid or expired. Please reconnect your account.", details: msg },
          { status: 401 }
        );
      }
      if (refRes.status === 403) {
        return NextResponse.json(
          { error: "Your token doesn't have permission to write to this repository. Make sure you have push access and the token has 'repo' scope.", details: msg },
          { status: 403 }
        );
      }
      return NextResponse.json(
        { error: `Failed to access repository: ${msg}` },
        { status: refRes.status }
      );
    }

    const refData = await refRes.json();
    const baseSha = refData.object.sha;

    // Step 2: Create a new branch
    const branchRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          ref: `refs/heads/${branch}`,
          sha: baseSha,
        }),
      }
    );

    if (!branchRes.ok) {
      const err = await branchRes.json().catch(() => ({}));
      return NextResponse.json(
        { error: `Failed to create branch: ${err.message || branchRes.status}` },
        { status: 500 }
      );
    }

    // Step 3: Create or update each file via the Contents API
    for (let i = 0; i < fixes.length; i++) {
      const file = fixes[i] as FixFile;

      // Check if file already exists
      const existingRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/contents/${file.path}?ref=${branch}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github.v3+json",
          },
        }
      );

      let existingSha: string | null = null;
      if (existingRes.ok) {
        const existingData = await existingRes.json();
        existingSha = existingData.sha;
      }

      // Create or update the file
      const contentEncoded = Buffer.from(file.content).toString("base64");

      const fileRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/contents/${file.path}`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github.v3+json",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            message: existingSha
              ? `[DevScore] Update ${file.path}`
              : `[DevScore] Add ${file.path}`,
            content: contentEncoded,
            branch,
            ...(existingSha ? { sha: existingSha } : {}),
          }),
        }
      );

      if (!fileRes.ok) {
        const err = await fileRes.json().catch(() => ({}));
        // Continue with other files even if one fails
        console.error(`Failed to write ${file.path}:`, err.message || fileRes.status);
      }
    }

    // Step 4: Create a Pull Request
    const fileList = fixes
      .map((f: FixFile) => `- ${f.icon} **\`${f.path}\`** — ${f.description}`)
      .join("\n");

    const prBody = `## 🔧 DevScore AI Repo Doctor

This PR was automatically generated by [DevScore.ai](https://devscore.ai) to improve your repository.

### Changes Made

${fileList}

### Description

Based on an AI-powered analysis of this repository, the following improvements were automatically generated to enhance code quality, documentation, and developer experience.

### Why This Matters

These improvements will:
- 📈 Increase your DevScore and hiring readiness
- 🎯 Make your repo more attractive to contributors and recruiters
- 🔒 Follow open-source best practices
- ⚡ Add CI/CD for automated testing

### Review Checklist

- [ ] Verify the changes work with your project
- [ ] Update any placeholder content (e.g., license name, tester email)
- [ ] Merge when ready

---

<sub>Generated by [DevScore.ai](https://devscore.ai) — AI-powered GitHub repository analysis and improvement</sub>`;

    const prRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/pulls`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title: "🔧 [DevScore] AI-powered repository improvements",
          head: branch,
          base: defaultBranch || "main",
          body: prBody,
          maintainer_can_modify: true,
        }),
      }
    );

    if (!prRes.ok) {
      const err = await prRes.json().catch(() => ({}));
      return NextResponse.json(
        {
          error: `Failed to create PR: ${err.message || prRes.status}`,
          branchUrl: `https://github.com/${owner}/${repo}/tree/${branch}`,
        },
        { status: 500 }
      );
    }

    const prData = await prRes.json();

    return NextResponse.json({
      success: true,
      prUrl: prData.html_url,
      prNumber: prData.number,
      branch,
      message: `Pull request #${prData.number} created successfully!`,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "PR creation failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
